version: '3.9'

services:
  core-di-stats-handler-gen1:
    container_name: core-di-stats-handler-gen1
    profiles:
      - mysql
      - mariadb
    build:
      dockerfile: Dockerfile
      target: dev
      context: .
      args:
        PIP_EXTRA_INDEX_URL: ${PIP_EXTRA_INDEX_URL}
    command: ["ipython", "solution/channel/fastapi/main.py"]
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - "./src/:/usr/src/app"
    env_file:
      - .env
    ports:
      - ${REST_SERVER_PORT}:${REST_SERVER_PORT}
    networks:
      - core-fkg-network

  core-di-stats-handler-gen1-stats-db-mysql:
    profiles:
      - mysql
    image: mysql:8.0.30
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_USER: ${DB_USERNAME}
    ports:
      - "3302:3306"
    volumes:
      - core-di-stats-handler-gen1-stats-db-volume-mysql:/var/lib/mysql
    networks:
      - core-fkg-network
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      interval: 5s
      timeout: 3s


  core-di-stats-handler-gen1-db-initializer-mysql:
    profiles:
      - mysql
    container_name: core-di-stats-handler-gen1-db-initializer-mysql
    build:
      dockerfile: Dockerfile
      target: mysql_migration
      context: .
      args:
        PIP_EXTRA_INDEX_URL: ${PIP_EXTRA_INDEX_URL}
    depends_on:
      core-di-stats-handler-gen1-stats-db-mysql:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - core-fkg-network
    volumes:
      - "./src/solution/sp/sql_base/mysql:/migrations"


  core-di-stats-handler-gen1-stats-db-mariadb:
    profiles:
      - mariadb
    image: mariadb:10.7
    environment:
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      MARIADB_ALLOW_EMPTY_PASSWORD: 1
      MARIADB_USER: ${DB_USERNAME}
    ports:
      - "3305:3306"
    volumes:
      - core-di-stats-handler-gen1-stats-db-volume-mariadb:/var/lib/mariadb
    networks:
      - core-fkg-network
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MARIADB_USER --password=$$MARIADB_PASSWORD
      interval: 5s
      timeout: 3s



  core-di-stats-handler-gen1-db-initializer-mariadb:
    profiles:
      - mariadb
    container_name: core-di-stats-handler-gen1-db-initializer-mariadb
    build:
      dockerfile: Dockerfile
      target: mariadb_migration
      context: .
      args:
        PIP_EXTRA_INDEX_URL: ${PIP_EXTRA_INDEX_URL}
    depends_on:
      core-di-stats-handler-gen1-stats-db-mariadb:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - core-fkg-network
    volumes:
      - "./src/solution/sp/sql_base/mariadb:/migrations"

volumes:
  core-di-stats-handler-gen1-stats-db-volume-mysql: {}
  core-di-stats-handler-gen1-stats-db-volume-mariadb: {}

networks:
  core-fkg-network:
    external: true
