"""empty message

Revision ID: 82c2737ed204
Revises: 615634176d43
Create Date: 2022-10-14 13:24:18.843737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82c2737ed204'
down_revision = '615634176d43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('request_source_uc', 'ingestion_status', ['request_id', 'source_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ingestion_status_ibfk_1', 'ingestion_status', type_='foreignkey')
    op.drop_constraint('request_source_uc', 'ingestion_status', type_='unique')
    op.create_foreign_key('ingestion_status_ibfk_1', 'ingestion_status', 'ingestion_request_status', ['request_id'], ['id'])
    # ### end Alembic commands ###
