"""empty message

Revision ID: 944aec9b9208
Revises: a90bf87a3ccd
Create Date: 2022-10-18 06:15:43.648146

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '944aec9b9208'
down_revision = 'a90bf87a3ccd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ingestion_request_filter', 'condition',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.String(length=64),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ingestion_request_filter', 'condition',
               existing_type=sa.String(length=64),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    # ### end Alembic commands ###
