"""empty message

Revision ID: a8c33c890791
Revises: 944aec9b9208
Create Date: 2022-11-04 14:17:58.005035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8c33c890791'
down_revision = '944aec9b9208'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_subscriber_ingestion_status', 'subscriber_ingestion_status', ['request_id', 'source_id', 'subscriber', 'file_uri'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_subscriber_ingestion_status', 'subscriber_ingestion_status', type_='unique')
    # ### end Alembic commands ###
