"""empty message

Revision ID: b7f720fee265
Revises: be68c0289c57
Create Date: 2022-09-13 10:25:09.323832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7f720fee265'
down_revision = 'be68c0289c57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
