"""empty message

Revision ID: 3be7712dc14a
Revises: 
Create Date: 2022-08-23 09:32:39.624311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3be7712dc14a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_request_status',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('tenant_id', sa.String(length=80), nullable=True),
    sa.Column('app_id', sa.String(length=80), nullable=True),
    sa.Column('entity_type', sa.String(length=80), nullable=True),
    sa.Column('src_type', sa.String(length=80), nullable=True),
    sa.Column('is_batch_required', sa.Boolean(), nullable=True),
    sa.Column('batch_size', sa.Integer(), nullable=True),
    sa.Column('enrich_oncreation', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=80), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingestion_request_filter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.String(length=128), nullable=True),
    sa.Column('attribute', sa.String(length=80), nullable=True),
    sa.Column('value', sa.String(length=256), nullable=True),
    sa.Column('condition', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['ingestion_request_status.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingestion_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.String(length=128), nullable=True),
    sa.Column('source_id', sa.String(length=128), nullable=True),
    sa.Column('file_uri', sa.String(length=256), nullable=True),
    sa.Column('entity_type', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=80), nullable=True),
    sa.Column('is_error', sa.Boolean(), nullable=True),
    sa.Column('message', sa.String(length=256), nullable=True),
    sa.Column('total_record_count', sa.Integer(), nullable=True),
    sa.Column('total_failed_count', sa.Integer(), nullable=True),
    sa.Column('total_success_count', sa.Integer(), nullable=True),
    sa.Column('source_queue_name', sa.String(length=256), nullable=True),
    sa.Column('last_stat_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['ingestion_request_status.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscriber_ingestion_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.String(length=128), nullable=True),
    sa.Column('source_id', sa.String(length=128), nullable=True),
    sa.Column('file_uri', sa.String(length=256), nullable=True),
    sa.Column('subscriber', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=80), nullable=True),
    sa.Column('is_error', sa.Boolean(), nullable=True),
    sa.Column('message', sa.String(length=256), nullable=True),
    sa.Column('total_record_count', sa.Integer(), nullable=True),
    sa.Column('total_failed_count', sa.Integer(), nullable=True),
    sa.Column('total_success_count', sa.Integer(), nullable=True),
    sa.Column('status_url', sa.String(length=256), nullable=True),
    sa.Column('last_stat_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['ingestion_request_status.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscriber_ingestion_status')
    op.drop_table('ingestion_status')
    op.drop_table('ingestion_request_filter')
    op.drop_table('ingestion_request_status')
    # ### end Alembic commands ###
