"""empty message

Revision ID: 693361d30936
Revises: 3be7712dc14a
Create Date: 2022-09-13 05:01:18.453116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '693361d30936'
down_revision = '3be7712dc14a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
