"""empty message

Revision ID: 873cfd295608
Revises: 693361d30936
Create Date: 2022-09-30 08:56:21.314557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '873cfd295608'
down_revision = '693361d30936'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingestion_request_status', sa.Column('subscriber_name', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingestion_request_status', 'subscriber_name')
    # ### end Alembic commands ###
