"""empty message

Revision ID: 958bb4c19f11
Revises: d4be30465cef
Create Date: 2022-11-04 08:43:43.073011

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '958bb4c19f11'
down_revision = 'd4be30465cef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ingestion_request_status', 'subscriber_name',
               existing_type=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               type_=sa.JSON(),
               existing_nullable=True)
    op.create_unique_constraint('unique_subscriber_ingestion_status', 'subscriber_ingestion_status', ['request_id', 'source_id', 'subscriber', 'file_uri'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_subscriber_ingestion_status', 'subscriber_ingestion_status', type_='unique')
    op.alter_column('ingestion_request_status', 'subscriber_name',
               existing_type=sa.JSON(),
               type_=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               existing_nullable=True)
    # ### end Alembic commands ###
