apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.name}}
type: Opaque
stringData:
  DB_ENDPOINT: {{.Values.db_endpoint}}
  DB_NAME: {{.Values.db_name}}
  DB_USERNAME: {{.Values.db_username}}
  DB_PASSWORD: {{.Values.db_password}}
  DB_TYPE: {{.Values.db_type}}
  DB_SSL_PATH_CERT: {{.Values.db_ssl_path_cert}}