apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.name}}
  annotations:
    maintainer.team: {{.Values.maintainer_team}}
    maintainer.contact: {{.Values.maintainer_contact}}
type: Opaque
stringData:
  DB_ENDPOINT: {{.Values.db_endpoint}}
  DB_NAME: {{.Values.db_name}}
  DB_USERNAME: {{.Values.db_username}}
  DB_PASSWORD: {{.Values.db_password}}
  DB_TYPE: {{.Values.db_type}}
  DB_SSL_PATH_CERT: {{.Values.db_ssl_path_cert}}
  AZURE_CLIENT_ID: {{.Values.azure_client_id}}
  AUTHENTICATOR_URL: {{.Values.authenticator_url}}