apiVersion: v1
kind: Service
metadata:
  name: {{.Values.service.name}}
  annotations:
    maintainer.team: {{.Values.maintainer_team}}
    maintainer.contact: {{.Values.maintainer_contact}}
spec:
  ports:
    - port: {{.Values.service.port}}
  selector:
    app: {{.Values.metadata.name}}
  type: ClusterIP