#!/bin/sh

mysql -h$DB_ENDPOINT -u$DB_USERNAME -p$DB_PASSWORD --ssl-ca $DB_SSL_PATH_CERT -e \
  "CREATE DATABASE IF NOT EXISTS  ${DB_NAME} /*\!40100 DEFAULT CHARACTER SET utf8 */;";

mysql -h$DB_ENDPOINT -u$DB_USERNAME -p$DB_PASSWORD --ssl-ca $DB_SSL_PATH_CERT -e \
    "GRANT ALL PRIVILEGES ON ${DB_NAME}.* TO '${DB_USERNAME}';";
mysql -h$DB_ENDPOINT -u$DB_USERNAME -p$DB_PASSWORD --ssl-ca $DB_SSL_PATH_CERT -e "FLUSH PRIVILEGES;";

alembic upgrade head